node ("maven-jenkins-plugin") {
    stage('Checkout') {
        cleanWs()
        checkout scm
    }
    stage('Build') {
        try {
            sh("make --version")
            sh("mvn --version")
                withEnv(['DOCKER_COMMAND=sh -c']) {
                    sh("make package")
                }
        } catch(err) {
            currentBuild.result = 'UNSTABLE'
            throw(err)
        }
    }
}
